[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements_crewai.txt"

[deploy]
startCommand = "python main_crewai.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
PYTHON_VERSION = "3.11"
